import io
import logging
from pathlib import Path

from tqdm import tqdm

from .config import Config, CustomRule, OutputConfig, TypeConfig
from .constants import PoolName, RuleName
from .emitter import NinjaEmitter
from .plugins import PluginInterface, load_plugin
from .rules import get_builtin_rules
from .utils import (
    get_recursive_yaml_deps,
    ninja_escape,
    parse_frontmatter_type,
    sanitize_path,
    should_process_file,
)

logger = logging.getLogger(__name__)


class NinjaGenerator:
    """Generates Ninja build files for a static site pipeline.

    The build process has these stages:
    1. Compile: Markdown → JSON (Pandoc AST)
    2. Render: JSON → Output format (HTML, PDF, etc)
    3. Post-process: Output → Optimized (minify, compress)
    4. Derive: Output → Derived format (HTML → PDF via Decktape)
    """

    def __init__(self, config: Config, config_path: Path, quiet: bool = False):
        """Initialize the NinjaBuilder."""
        self.config = config
        self.config_path = config_path.resolve()
        self.quiet = quiet

        # Configure paths
        self.src = Path(self.config.src_dir).resolve()
        self.out_dir = Path(self.config.output_dir).resolve()
        self.build_dir = Path(self.config.build_dir).resolve()
        self.ninja_file = self.build_dir / "build.ninja"

        # Create build directory
        self.build_dir.mkdir(parents=True, exist_ok=True)

        # Buffer and Emitter
        self._buffer = io.StringIO()
        self.emitter = NinjaEmitter(self._buffer)

        # Track all final outputs
        self.all_outputs: list[Path] = []

        # Load plugins
        self.plugins: list[PluginInterface] = []
        for plugin_path in self.config.plugins:
            plugin = load_plugin(plugin_path)
            if plugin:
                self.plugins.append(plugin)

        # Collect rules: Built-in + Config Custom + Plugin Custom
        self.rules: list[CustomRule] = get_builtin_rules(self.config, self.config_path)
        self.rules.extend(self.config.custom_rules)
        for plugin in self.plugins:
            self.rules.extend(plugin.get_custom_rules())

    def _get_merged_defaults(self, *sources: str | list[str] | None) -> list[Path]:
        """Merge default files from multiple sources and return absolute paths."""
        merged = []
        for src in sources:
            if not src:
                continue
            if isinstance(src, str):
                merged.append(Path(src))
            else:
                merged.extend(Path(s) for s in src)
        return merged

    def _format_defaults_var(self, defaults: list[Path]) -> str:
        """Format list of defaults into ninja variable string."""
        if not defaults:
            return ""
        return "-d " + " -d ".join(ninja_escape(d) for d in defaults)

    def emit_header(self) -> None:
        """Generate Ninja file header with version, pools, and rules."""
        self.emitter.comment("Auto-generated by dojo - DO NOT EDIT MANUALLY")
        self.emitter.comment(f"Source: {self.config_path}")
        self.emitter.newline()
        self.emitter.variable("ninja_required_version", "1.3")
        self.emitter.newline()

        # Pools
        self.emitter.comment("Resource pools prevent CPU/memory saturation")
        self.emitter.fp.write(f"pool {PoolName.HEAVY_PROCESSING.value}\n")
        self.emitter.variable("depth", "1", indent=1)
        self.emitter.newline()

        # Rules
        self.emitter.comment("Rules")
        for rule in self.rules:
            self.emitter.rule(
                name=rule.name,
                command=rule.command,
                description=rule.description,
                pool=rule.pool,
                depfile=rule.depfile,
                deps=rule.deps,
                generator=rule.generator,
                variables=rule.variables,
            )

            # Special case for REGENERATE: emit the build edge immediately
            if rule.name == RuleName.REGENERATE.value:
                self.emitter.build(
                    outputs=self.ninja_file,
                    rule=RuleName.REGENERATE.value,
                    inputs=self.config_path,
                )
                self.emitter.newline()

    def _compile_stage(self, md_path: Path, rel_stem: Path, type_config: TypeConfig) -> Path:
        """Convert Markdown to JSON (Pandoc AST)."""
        json_node = sanitize_path(self.build_dir, rel_stem.with_suffix(".json"))

        compile_defaults = self._get_merged_defaults(self.config.defaults, type_config.defaults)
        variables = {}
        implicit = []

        if compile_defaults:
            variables["defaults"] = self._format_defaults_var(compile_defaults)
            # Find a way to add implicit dependencies. NinjaEmitter.build supports it.
            # but wait, the original code added them with " | "
            # So I should pass them to implicit.
            # _get_dep_string returns a string, I need paths.
            raw_deps = []
            for df in compile_defaults:
                raw_deps.append(df)
                raw_deps.extend(get_recursive_yaml_deps(df))
            implicit = sorted(set(raw_deps))

        self.emitter.build(
            outputs=json_node,
            rule=RuleName.COMPILE.value,
            inputs=md_path,
            implicit=implicit,
            variables=variables,
        )
        return json_node

    def _render_stage(
        self,
        out_config: OutputConfig,
        json_node: Path,
        rel_stem: Path,
        local_registry: dict[str, Path],
    ) -> None:
        """Convert JSON to Output format or Derived Output."""
        if out_config.source:
            self._derive_output(out_config, rel_stem, local_registry)
        else:
            self._standard_render(out_config, rel_stem, json_node, local_registry)

    def _standard_render(
        self,
        out_config: OutputConfig,
        rel_stem: Path,
        json_node: Path,
        local_registry: dict[str, Path],
    ) -> None:
        """Render standard Pandoc with optional post-processing."""
        filename = f"{rel_stem.name}{out_config.suffix}.{out_config.extension}"
        final_path = sanitize_path(self.out_dir, rel_stem.parent / filename)

        post_tool = out_config.post_process
        if post_tool:
            render_target = sanitize_path(
                self.build_dir, Path("intermediates") / rel_stem.parent / filename
            )
        else:
            render_target = final_path

        # Gather dependencies for rendering
        all_defaults = self._get_merged_defaults(out_config.defaults)
        variables = {}
        implicit = []

        if all_defaults:
            variables["defaults"] = self._format_defaults_var(all_defaults)
            raw_deps = []
            for df in all_defaults:
                raw_deps.append(df)
                raw_deps.extend(get_recursive_yaml_deps(df))
            implicit = sorted(set(raw_deps))

        if out_config.args:
            variables["args"] = " ".join(out_config.args)

        self.emitter.build(
            outputs=render_target,
            rule=RuleName.RENDER.value,
            inputs=json_node,
            implicit=implicit,
            variables=variables,
        )

        if post_tool:
            self.emitter.build(outputs=final_path, rule=post_tool, inputs=render_target)

        if out_config.id:
            local_registry[out_config.id] = final_path

        self.all_outputs.append(final_path)

    def _derive_output(
        self, out_config: OutputConfig, rel_stem: Path, local_registry: dict[str, Path]
    ) -> None:
        """Derive output from other build products (e.g. HTML -> PDF)."""
        filename = f"{rel_stem.name}{out_config.suffix}.{out_config.extension}"
        final_path = sanitize_path(self.out_dir, rel_stem.parent / filename)

        raw_source = out_config.source
        if out_config.source is None:
            raise ValueError("Output source cannot be None")
        raw_source = out_config.source

        source_ids_list: list[str] = [raw_source] if isinstance(raw_source, str) else raw_source

        source_paths = []
        for parent_id in source_ids_list:
            if parent_id not in local_registry:
                logger.error(f"Missing dependency '{parent_id}' for output '{out_config.id}'")
                raise ValueError(f"Missing dependency: {parent_id}")
            source_paths.append(local_registry[parent_id])

        variables = {}
        if out_config.args:
            variables["args"] = " ".join(out_config.args)

        if out_config.tool is None:
            raise ValueError("Output tool cannot be None")

        self.emitter.build(
            outputs=final_path,
            rule=out_config.tool,
            inputs=source_paths,
            variables=variables,
        )

        if out_config.id:
            local_registry[out_config.id] = final_path

        self.all_outputs.append(final_path)

    def process_content(self, md_path: Path) -> None:
        """Generate Ninja build rules for a single Markdown source file."""
        try:
            rel_path = md_path.relative_to(self.src)
        except ValueError:
            logger.error(f"Source file outside source directory: {md_path}")
            return

        rel_stem = rel_path.with_suffix("")

        # Identify content type
        content_type = parse_frontmatter_type(md_path, self.config.default_type)
        type_config = self.config.types.get(
            content_type, self.config.types[self.config.default_type]
        )

        # Stage 1: Compile
        try:
            src_comment = md_path.relative_to(Path.cwd())
        except ValueError:
            src_comment = md_path

        self.emitter.comment(f"Source: {src_comment}")
        json_node = self._compile_stage(md_path, rel_stem, type_config)
        self.emitter.newline()

        if not type_config.outputs:
            return

        # Stage 2: Render/Derive
        local_registry: dict[str, Path] = {}
        for out_config in type_config.outputs:
            # Plugin Hook: Modify output config
            for plugin in self.plugins:
                out_config = plugin.modify_output_config(out_config, content_type)

            self._render_stage(out_config, json_node, rel_stem, local_registry)

        self.emitter.newline()

    def generate(self) -> None:
        """Scan source files and generate build.ninja."""
        logger.info(f"Scanning source directory: {self.src}")

        self.emit_header()

        md_files = sorted(self.src.rglob("*.md"))
        filtered_files = [
            f
            for f in md_files
            if should_process_file(f, self.src, self.config.include, self.config.exclude)
        ]

        if not filtered_files:
            logger.warning(f"No Markdown files found in {self.src}")
        else:
            logger.info(f"Found {len(filtered_files)} Markdown file(s)")

        for md_file in tqdm(filtered_files, desc="Processing", unit="file", disable=self.quiet):
            try:
                self.process_content(md_file)
            except Exception as e:
                logger.error(f"Failed to process {md_file}: {e}")
                raise

        ninja_content = self._buffer.getvalue()

        # Plugin Hook: Post-process Ninja content
        for plugin in self.plugins:
            ninja_content = plugin.post_process_ninja(ninja_content)

        try:
            with open(self.ninja_file, "w", encoding="utf-8") as f:
                f.write(ninja_content)
        except Exception as e:
            logger.error(f"Failed to write {self.ninja_file}: {e}")
            raise

        logger.info(f"Generated: {self.ninja_file}")
        logger.info(f"Outputs: {len(self.all_outputs)} file(s) will be built")
        logger.info("")
        logger.info("Next steps:")
        try:
            rel_ninja = self.ninja_file.relative_to(Path.cwd())
        except ValueError:
            rel_ninja = self.ninja_file
        logger.info(f"  ninja -f {rel_ninja}")
