name: Publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
    
    - name: Build
      run: nix develop --command bash -c "python -m build"

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
